### ISSUE TITLE
Docker-compose.yml requires compose v2 (Readme issue)  /  .env path mismatch (environment specific?) in docker-compose

### ISSUE THREAD

**Issue by milankubin** [elie222/inbox-zero#401]
https://github.com/elie222/inbox-zero/blob/1f3bb2b3f486ffa393430c4547d4b2c0fee6e466/docker-compose.yml#L45

Running on Debian, docker-compose.yml does not work on v1.x versions of compose (Default for any Debian stable release):
``` bash
└╼milan$docker-compose up -d 
ERROR: The Compose file './../../docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'
```

Had to install docker-compose v2 from experimental branch, then:

``` bash
docker-compose up -a
```
now becomes 
``` bash
docker compose up -a
```

produces the following error
``` bash
WARN[0000] The "UPSTASH_REDIS_TOKEN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "UPSTASH_REDIS_TOKEN" variable is not set. Defaulting to a blank string. 
env file <omitted_local_path>/inbox-zero/.env not found: stat <omitted_local_path>/inbox-zero/.env: no such file or directory
```
Updating aforementioned line in docker-compose to use './apps/web/.env'  fixed the issue.

**Comment by vishalmakwana111** [comment]
Hi @elie222, I've opened PR #411 to address the `env_file` path confusion mentioned in this issue. It changes the `docker-compose.yml` file to point the `web` service's `env_file` directly to `apps/web/.env`, simplifying the setup for Docker users.

**Comment by eethann** [comment]
I just ran into the UPSTASH_REDIS_TOKEN issue when installing locally. The specific issue, as I understand it, is that the docker-compose.yml file looks to the "root" environment for variables, not the `apps/web/.env` environment. I think this can be 

I addressed it with a quick short-term fix:

```
export UPSTASH_REDIS_TOKEN=token-string-here
```

And then I created a .env at the root level of the project with the `UPSTASH_REDIS_TOKEN` env variable.

That seems to work on a restart of the docker container, but I'm not convinced it's not relying on the old env var.

**Comment by KarolKozlowski** [comment]
The file `apps/web/.env` does NOT exist in the repository which breaks the compose file - this should exist and contain reasonable defaults. Currently it points to a non existing file and breaks the config:

```
❯ docker compose config
WARN[0000] The "UPSTASH_REDIS_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "UPSTASH_REDIS_TOKEN" variable is not set. Defaulting to a blank string.
env file /home/karol.kozlowski/wa/inbox-zero/apps/web/.env not found: stat /home/karol.kozlowski/wa/inbox-zero/apps/web/.env: no such file or directory
```

As a result it breaks any form of managing multiple compose files (overrides) described in the official documentation: https://docs.docker.com/compose/how-tos/multiple-compose-files/

I've opened #954 to address this.

**Comment by cardaba** [comment]
Still reproducing this today (2026-08-31) on `ghcr.io/elie222/inbox-zero:latest`, self-hosted via the `npx @inbox-zero/cli setup` Quick Setup flow, so re-opening this thread rather than filing a duplicate.

## What's actually happening

PR #411 pointed the `web` service's `env_file` at `apps/web/.env`, which fixed *that* service's runtime environment — but `docker-compose.yml:51` still does:

```yaml
serverless-redis-http:
  environment:
    SRH_TOKEN: ${UPSTASH_REDIS_TOKEN}
```

`${UPSTASH_REDIS_TOKEN}` here is resolved by **Docker Compose itself at YAML-parse time**, which only looks at the shell environment or a `.env` file in the **project root** — `env_file:` on a service has no effect on this, since that only injects vars *into the container*, after Compose has already resolved the YAML. Since the CLI wizard only writes `apps/web/.env` (not a root `.env`), `${UPSTASH_REDIS_TOKEN}` resolves to an empty string for `serverless-redis-http`'s `SRH_TOKEN`, while the `web`/`worker`/`cron` containers get the *real* token via `env_file`. Result: `web` calls the Upstash-compatible REST API with a token `serverless-redis-http` doesn't recognize.

## Symptom

```
[api]: Failed to read provider rate-limit state {
  "emailAccountId": "...",
  "error": "Invalid token, command was: [[\"get\",\"email-provider-rate-limit:...\"]]"
}
```

Same underlying cause as the "Failed to read provider rate-limit state" warnings in #2227.

## Workaround

Create a `.env` at the **repo root** (not `apps/web/.env`) containing at least:

```
UPSTASH_REDIS_TOKEN=<same value as in apps/web/.env>
```

then `docker compose --profile all up -d --force-recreate serverless-redis-http`. Confirmed this fixes it — `SRH_TOKEN` inside the container then matches what `web` sends.

## Suggested real fix

Either:
- Have the CLI wizard also write (or symlink) a root-level `.env` with the Compose-only variables it needs (`UPSTASH_REDIS_TOKEN` at minimum), or
- Change `docker-compose.yml` to not rely on Compose-level substitution for `SRH_TOKEN` — e.g. have `serverless-redis-http` also read it from `env_file: ./apps/web/.env` if that's achievable for this image, or generate a fixed/matching value some other way.

Happy to test a fix against my self-hosted instance if useful.
